name: phuthanh_warehouseapp
description: "Phú Thành WareHouse"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  advanced_dropdown: ^2.0.5
  dartssh2: ^2.13.0
  flutter:
    sdk: flutter
  http: ^1.5.0
  image_picker: ^1.2.0
  mobile_scanner: ^6.0.11
  shared_preferences: ^2.5.3
  show_hide_password: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
